#pragma once

typedef enum {
    SYSCALL_READ,
    SYSCALL_WRITE,
    SYSCALL_OPEN,
    SYSCALL_CLOSE,
    SYSCALL_STAT,
    SYSCALL_FSTAT,
    SYSCALL_LSTAT,
    SYSCALL_POLL,
    SYSCALL_LSEEK,
    SYSCALL_MEMMAP,
    SYSCALL_GET_FB,
    SYSCALL_GET_KB,
    SYSCALL_PRINT,
    SYSCALL_PRINT_PTR,
    SYSCALL_KB_READ,
    SYSCALL_SLEEP,
} syscalls_call;