#pragma once

typedef enum {
    SYSCALL_READ,
    SYSCALL_WRITE,
    SYSCALL_OPEN,
    SYSCALL_CLOSE,
    SYSCALL_STAT,
    SYSCALL_FSTAT,
    SYSCALL_LSTAT,
    SYSCALL_POLL,
    SYSCALL_LSEEK,
    SYSCALL_MEMMAP,
    SYSCALL_GET_FB,
    SYSCALL_GET_KB,
    SYSCALL_PRINT,
    SYSCALL_PRINT_PTR,
    SYSCALL_KB_READ,
    SYSCALL_SLEEP,
    SYSCALL_GETDENTS,
} syscalls_call;

#define SYSCALL_OPEN_FLAG_READ 0x1
#define SYSCALL_OPEN_FLAG_WRITE 0x2
#define SYSCALL_OPEN_FLAG_CREATE 0x4
#define SYSCALL_OPEN_FLAG_DIRECTORY 0x8