#ifndef _PLENJOS_DEV_KEYCODES_H
#define _PLENJOS_DEV_KEYCODES_H 1

#include "stdint.h"

/**
 * Keyboard codes
 */
enum key_codes {
    KEY_NONE         = 0,
    KEY_ESC          = 0x01,
    KEY_F1           = 0x02,
    KEY_F2           = 0x03,
    KEY_F3           = 0x04,
    KEY_F4           = 0x05,
    KEY_F5           = 0x06,
    KEY_F6           = 0x07,
    KEY_F7           = 0x08,
    KEY_F8           = 0x09,
    KEY_F9           = 0x0A,
    KEY_F10          = 0x0B,
    KEY_F11          = 0x0C,
    KEY_F12          = 0x0D,
    KEY_PRINT_SCREEN = 0x0E,
    KEY_SCROLL_LOCK  = 0x0F,
    KEY_PAUSE        = 0x10,
    KEY_INSERT       = 0x11,
    KEY_HOME         = 0x12,
    KEY_PAGE_UP      = 0x13,
    KEY_DELETE       = 0x14,
    KEY_END          = 0x15,
    KEY_PAGE_DOWN    = 0x16,
    KEY_UP           = 0x17,
    KEY_LEFT         = 0x18,
    KEY_DOWN         = 0x19,
    KEY_RIGHT        = 0x1A,
    KEY_NUM_LOCK     = 0x1B,
    KEY_KP_SLASH     = 0x1C,
    KEY_KP_ASTERISK  = 0x1D,
    KEY_KP_MINUS     = 0x1E,
    KEY_KP_PLUS      = 0x1F,
    KEY_KP_ENTER     = 0x20,
    KEY_KP_PERIOD    = 0x21,
    KEY_KP_CENTER    = 0x22,
    KEY_KP_0         = 0x23,
    KEY_KP_1         = 0x24,
    KEY_KP_2         = 0x25,
    KEY_KP_3         = 0x26,
    KEY_KP_4         = 0x27,
    KEY_KP_5         = 0x28,
    KEY_KP_6         = 0x29,
    KEY_KP_7         = 0x2A,
    KEY_KP_8         = 0x2B,
    KEY_KP_9         = 0x2C,
    KEY_LEFT_CTRL    = 0x2D,
    KEY_LEFT_SHIFT   = 0x2E,
    KEY_LEFT_ALT     = 0x2F,
    KEY_LEFT_META    = 0x30,
    KEY_RIGHT_CTRL   = 0x31,
    KEY_RIGHT_SHIFT  = 0x32,
    KEY_RIGHT_ALT    = 0x33,
    KEY_RIGHT_META   = 0x34,
    KEY_MENU         = 0x35,
    KEY_CAPS_LOCK    = 0x36,

    KEY_TAB       = 0x37,
    KEY_ENTER     = 0x38,
    KEY_BACKSPACE = 0x39,

    KEY_BACKTICK  = 0x3A,
    KEY_MINUS      = 0x3B,
    KEY_EQUALS    = 0x3C,
    KEY_LBRACK    = 0x3D,
    KEY_RBRACK    = 0x3E,
    KEY_BACKSLASH = 0x3F,
    KEY_SEMICOLON = 0x40,
    KEY_QUOTE     = 0x41,
    KEY_COMMA     = 0x42,
    KEY_PERIOD    = 0x43,
    KEY_SLASH     = 0x44,
    KEY_SPACE     = 0x45,

    /* Start of normal text characters */
    KEY_A = 0x80,
    KEY_B = 0x81,
    KEY_C = 0x82,
    KEY_D = 0x83,
    KEY_E = 0x84,
    KEY_F = 0x85,
    KEY_G = 0x86,
    KEY_H = 0x87,
    KEY_I = 0x88,
    KEY_J = 0x89,
    KEY_K = 0x8A,
    KEY_L = 0x8B,
    KEY_M = 0x8C,
    KEY_N = 0x8D,
    KEY_O = 0x8E,
    KEY_P = 0x8F,
    KEY_Q = 0x90,
    KEY_R = 0x91,
    KEY_S = 0x92,
    KEY_T = 0x93,
    KEY_U = 0x94,
    KEY_V = 0x95,
    KEY_W = 0x96,
    KEY_X = 0x97,
    KEY_Y = 0x98,
    KEY_Z = 0x99,
    KEY_1 = 0x9A,
    KEY_2 = 0x9B,
    KEY_3 = 0x9C,
    KEY_4 = 0x9D,
    KEY_5 = 0x9E,
    KEY_6 = 0x9F,
    KEY_7 = 0xA0,
    KEY_8 = 0xA1,
    KEY_9 = 0xA2,
    KEY_0 = 0xA3,

    KEY_UNKNOWN = 0xFF,
};

enum key_mods {
    KBD_MOD_SHIFT    = 0x01,
    KBD_MOD_CAPSLOCK = 0x02,
    KBD_MOD_CTRL     = 0x04,
    KBD_MOD_ALT      = 0x08,
    KBD_MOD_META     = 0x10,
};

static const uint8_t map_uppercase[256] = {
    [KEY_TAB] = '\t',
    [KEY_ENTER] = '\n',
    [KEY_BACKSPACE] = '\b',
    [KEY_BACKTICK] = '~',
    [KEY_MINUS] = '_',
    [KEY_EQUALS] = '+',
    [KEY_LBRACK] = '{',
    [KEY_RBRACK] = '}',
    [KEY_BACKSLASH] = '|',
    [KEY_SEMICOLON] = ':',
    [KEY_QUOTE] = '"',
    [KEY_COMMA] = '<',
    [KEY_PERIOD] = '>',
    [KEY_SLASH] = '?',
    [KEY_SPACE] = ' ',
    [KEY_A] = 'A',
    [KEY_B] = 'B',
    [KEY_C] = 'C',
    [KEY_D] = 'D',
    [KEY_E] = 'E',
    [KEY_F] = 'F',
    [KEY_G] = 'G',
    [KEY_H] = 'H',
    [KEY_I] = 'I',
    [KEY_J] = 'J',
    [KEY_K] = 'K',
    [KEY_L] = 'L',
    [KEY_M] = 'M',
    [KEY_N] = 'N',
    [KEY_O] = 'O',
    [KEY_P] = 'P',
    [KEY_Q] = 'Q',
    [KEY_R] = 'R',
    [KEY_S] = 'S',
    [KEY_T] = 'T',
    [KEY_U] = 'U',
    [KEY_V] = 'V',
    [KEY_W] = 'W',
    [KEY_X] = 'X',
    [KEY_Y] = 'Y',
    [KEY_Z] = 'Z',
    [KEY_1] = '!',
    [KEY_2] = '@',
    [KEY_3] = '#',
    [KEY_4] = '$',
    [KEY_5] = '%',
    [KEY_6] = '^',
    [KEY_7] = '&',
    [KEY_8] = '*',
    [KEY_9] = '(',
    [KEY_0] = ')',
};

static const uint8_t map_lowercase[256] = {
    [KEY_TAB] = '\t',
    [KEY_ENTER] = '\n',
    [KEY_BACKSPACE] = '\b',
    [KEY_BACKTICK] = '`',
    [KEY_MINUS] = '-',
    [KEY_EQUALS] = '=',
    [KEY_LBRACK] = '[',
    [KEY_RBRACK] = ']',
    [KEY_BACKSLASH] = '\\',
    [KEY_SEMICOLON] = ';',
    [KEY_QUOTE] = '\'',
    [KEY_COMMA] = ',',
    [KEY_PERIOD] = '.',
    [KEY_SLASH] = '/',
    [KEY_SPACE] = ' ',
    [KEY_A] = 'a',
    [KEY_B] = 'b',
    [KEY_C] = 'c',
    [KEY_D] = 'd',
    [KEY_E] = 'e',
    [KEY_F] = 'f',
    [KEY_G] = 'g',
    [KEY_H] = 'h',
    [KEY_I] = 'i',
    [KEY_J] = 'j',
    [KEY_K] = 'k',
    [KEY_L] = 'l',
    [KEY_M] = 'm',
    [KEY_N] = 'n',
    [KEY_O] = 'o',
    [KEY_P] = 'p',
    [KEY_Q] = 'q',
    [KEY_R] = 'r',
    [KEY_S] = 's',
    [KEY_T] = 't',
    [KEY_U] = 'u',
    [KEY_V] = 'v',
    [KEY_W] = 'w',
    [KEY_X] = 'x',
    [KEY_Y] = 'y',
    [KEY_Z] = 'z',
    [KEY_1] = '1',
    [KEY_2] = '2',
    [KEY_3] = '3',
    [KEY_4] = '4',
    [KEY_5] = '5',
    [KEY_6] = '6',
    [KEY_7] = '7',
    [KEY_8] = '8',
    [KEY_9] = '9',
    [KEY_0] = '0',
};

#endif /* _PLENJOS_DEV_KEYCODES_H */